---
- hosts: 172.25.1.20
  become: true
  tasks:
  - name: Copy file in remote system
    copy: src="urlsfile.sh"  dest="/usr/bin" mode=0755

  - name: Log Generation from squid server
    shell: urlsfile.sh
